/* Auto-generated by @antadesign/anta. Do not edit by hand. */

import type { IconShapes } from '@antadesign/anta'

export const ICON_SHAPES = [
  'book-a',
  'circle-pause',
  'circle-play',
  'octagon-pause',
  'sticker',
] as const

export const ICON_SYNONYMS: Readonly<Record<string, readonly string[]>> = {
}

declare module '@antadesign/anta' {
  interface IconShapes {
    'book-a': true
    'circle-pause': true
    'circle-play': true
    'octagon-pause': true
    'sticker': true
  }
}

export type IconShape = keyof IconShapes
